### ISSUE TITLE
Add make targets for macOS x86_64/arm64 release builds

### ISSUE THREAD

**Issue by Youw** [seeraven/gitcache#30]

**Comment by Youw** [comment]
I've tested that the project works on macOS (ARM64) when executed from git tree just fine. PIP dependencies I've used the same as for Ubuntu.
I guess it should be just a matter of defining a release target. (Assuming make4py supports macOS).

**Comment by seeraven** [comment]
I'm not owning any Apple product, and apparently there is no out-of-the-box qemu that I could use for testing and building the releases. Seems like that is intended by Apple.

https://github.com/seeraven/make4py should run on any platform supporting `make` and having a minimal python ecosystem. But for building the building the binaries using pyInstaller, it has to run in the actual target environment, which would require something like a VM resp. QEMU to get from Intel to ARM64.

Perhaps it would be sufficient to build it on a compatible platform. Do you know whether there are some compatible systems out there that are already usable as VirtualBox/Qemu/Vagrant boxes?

**Comment by Youw** [comment]
No, never used anything like that myself.
But we could make even one step further: start using Github Actions for automatic builds. There are native macOS Runners available.
I have a good example of such: https://github.com/libusb/hidapi/blob/master/.github/workflows/builds.yml

And I have a macOS (M1) machine, to try things locally.

Even supporting only native builds would be already a huge step forward.

**Comment by amontalban** [comment]
Hello :wave:,

I am in the process to test this tool and having a native ARM64 build would be great to test things outside our CI/CD environment.

Let me know if you need help testing things out.

**Comment by seeraven** [comment]
Short update on the current state: I've managed to use the github actions to test everything and create the pyinstaller binaries. Next steps are:
  - Integrate the changes to make4py.
  - Create a github action to build the pip-deps for all platforms, especially macos as I can't create them on my machine.
  - Create a github action to build the releases.

Once I have the first releases built on github, I can test the Linux and Windows releases, but it would be cool if you can then test the MacOS release. :-)

**Comment by seeraven** [comment]
So, the first release built using github runners and including the MacOS arm64 built is now available: https://github.com/seeraven/gitcache/releases/tag/v1.0.15 

I'm currently testing the Ubuntu and Windows binaries. Would be cool if someone can test the MacOS version. :-)

**Comment by amontalban** [comment]
It worked very well in my macOS machine (M1 Pro).

**Comment by seeraven** [comment]
Thanks for your feedback @amontalban ! :-) I will close this issue then.
